{application,erlang_tpke,
             [{registered,[]},
              {description,"Erlang implementation of TPKE"},
              {vsn,"0.1.0"},
              {applications,[kernel,stdlib,erlang_pbc]},
              {env,[]},
              {maintainers,["Helium"]},
              {licenses,["Apache 2.0"]},
              {links,[{"Github","https://github.com/helium/erlang-tpke"}]},
              {modules,[dealer,tpke_privkey,tpke_pubkey]}]}.
